[azure]
key = "DMHPeVQuJfZvrsGn80nuci7SByjEVtooq9AltGAlh3fqNSBauOcHJQQJ99BEACqBBLyXJ3w3AAAFACOGor89"
endpoint = "https://prefabparser.cognitiveservices.azure.com/"

[ocr_space]
key = "K87192763488957"
